# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsBu2W-7jRTkjfQLJ2W7XHotCgrHy7N_
"""

# =========================================
# app.py
# =========================================
import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from streamlit_folium import folium_static
import folium
import os

# ================================
# 🔹 Load pre-trained model
# ================================
MODEL_PATH = "model_rf_hargapenawaran.joblib"

if os.path.exists(MODEL_PATH):
    model_rf = joblib.load(MODEL_PATH)
    st.session_state["model_rf"] = model_rf
else:
    st.warning("⚠️ File model_rf_hargapenawaran.joblib belum ada. Harap siapkan model pre-trained.")

# ================================
# 🔹 Sidebar: Upload Data
# ================================
st.sidebar.header("📤 Upload Data")
uploaded_file = st.sidebar.file_uploader("Upload Excel/CSV dataset", type=["csv", "xlsx"])

if uploaded_file:
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)
    st.success("✅ Dataset berhasil diunggah!")
    st.write("Preview Dataset:")
    st.dataframe(df.head())

    # ================================
    # 🔹 Tampilkan hasil model evaluation (results)
    # ================================
    st.header("📊 Evaluasi Model")
    st.info("Analisis dilakukan menggunakan Random Forest secara default.")

    target = 'HARGAPENAWARAN'
    X = df.drop(columns=[target])
    y = df[target]
    X = X.loc[:, X.nunique() > 1]

    if "model_rf" in st.session_state:
        model_rf = st.session_state["model_rf"]
        # Prediksi in-sample & out-sample (split 80:20)
        from sklearn.model_selection import train_test_split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=77)
        y_train_pred = model_rf.predict(X_train)
        y_test_pred = model_rf.predict(X_test)
        results = pd.DataFrame([{
            'R2_in_sample': model_rf.score(X_train, y_train),
            'R2_out_sample': model_rf.score(X_test, y_test),
            'RMSE_in_sample': np.sqrt(np.mean((y_train - y_train_pred)**2)),
            'RMSE_out_sample': np.sqrt(np.mean((y_test - y_test_pred)**2)),
            'MAE_in_sample': np.mean(np.abs(y_train - y_train_pred)),
            'MAE_out_sample': np.mean(np.abs(y_test - y_test_pred))
        }])
        st.dataframe(results.T, width=600)

    # ================================
    # 🔹 Prediksi Data Baru
    # ================================
    st.header("💡 Prediksi Harga & Top-5 Similarity")
    st.subheader("Input Variabel")

    input_data = {}
    for col in X.columns:
        val = st.number_input(f"{col}", value=float(X[col].median()))
        input_data[col] = val
    input_df = pd.DataFrame([input_data])

    if st.button("Prediksi Harga"):
        pred_harga = model_rf.predict(input_df)[0]
        st.success(f"💰 Prediksi Harga: {pred_harga:,.2f}")

        # Top-5 similarity
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        input_scaled = scaler.transform(input_df)
        sim_matrix = cosine_similarity(X_scaled, input_scaled)
        top5_idx = np.argsort(sim_matrix[:,0])[::-1][:5]
        st.subheader("Top-5 Similar Data Points (Index & Score)")
        top5_df = pd.DataFrame({
            "Index": top5_idx,
            "Similarity": sim_matrix[top5_idx,0]
        })
        st.dataframe(top5_df)

    # ================================
    # 🔹 Fitur Koordinat Baru
    # ================================
    st.header("📍 Analisis Koordinat Baru")
    lat = st.number_input("Latitude", value=float(df['LATITUDE'].median()))
    lon = st.number_input("Longitude", value=float(df['LONGITUDE'].median()))

    if st.button("Hitung Jarak & Landuse"):
        # pastikan file my_osm_functions.py ada di folder sama
        from my_osm_functions import visualisasi_peta_adaptif_network, summary_koordinat_v5_7

        tmp_df = pd.DataFrame([{'LATITUDE': lat, 'LONGITUDE': lon}])
        m, hasil_df, df_detect = visualisasi_peta_adaptif_network(
            tmp_df, summary_koordinat_v5_7=summary_koordinat_v5_7
        )
        st.write("Hasil jarak ke jalan:")
        st.dataframe(hasil_df[['LATITUDE','LONGITUDE','Jarak_ke_JalanUtama','Jarak_ke_JalanSekunder']])
        st.write("Landuse / POI info:")
        st.dataframe(df_detect)

        st.subheader("🗺️ Peta Interaktif")
        folium_static(m)

